"use client";

import { motion, type Variants } from "motion/react";
import { ArrowDownRight, ArrowUpRight, ChevronRight } from "lucide-react";
import Link from "next/link";
import { basketballGroups, newsItems, timeline } from "@/data/content";
import { MediaPlaceholder } from "@/components/ui/placeholder";

const reveal: Variants = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: .7, ease: "easeOut" } } };

export function HomePage() { return <main>
  <section id="inicio" className="relative flex min-h-[92svh] items-end overflow-hidden bg-[var(--welcome-black)] text-white">
    <MediaPlaceholder className="absolute inset-0 min-h-0 opacity-20" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/35 to-transparent" />
    <div className="relative mx-auto w-full max-w-7xl px-6 pb-16 pt-36 lg:px-10 lg:pb-24"><motion.div initial="hidden" animate="visible" variants={reveal} className="max-w-5xl"><p className="mb-6 text-xs font-bold uppercase tracking-[.28em] text-[var(--welcome-red-light)]">Club Atlético Welcome · Placeholder</p><h1 className="display max-w-4xl text-[clamp(3.5rem,10vw,9.5rem)] font-extrabold leading-[.83] tracking-[-.09em]">Donde la historia<br /><span className="text-[var(--welcome-red)]">sigue jugando.</span></h1><p className="mt-8 max-w-md text-base leading-7 text-white/65">Un lugar para el básquet, la comunidad y todas las generaciones que hacen Welcome.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#socios" className="inline-flex items-center gap-3 rounded-full bg-[var(--welcome-red)] px-6 py-4 text-sm font-bold transition-transform hover:scale-105">Hacete socio <ArrowUpRight size={17} /></a><a href="#basquet" className="inline-flex items-center gap-3 rounded-full border border-white/30 px-6 py-4 text-sm font-bold hover:bg-white hover:text-black">Conocé Welcome <ArrowDownRight size={17} /></a></div></motion.div></div>
    <div className="absolute bottom-8 right-6 hidden text-right text-xs uppercase tracking-[.18em] text-white/40 lg:block">Contenido visual<br />pendiente de reemplazar</div>
  </section>

  <section className="bg-[var(--welcome-red)] px-6 py-24 text-white lg:px-10 lg:py-36"><motion.div initial="hidden" whileInView="visible" viewport={{ once: true, amount: .35 }} variants={reveal} className="mx-auto max-w-7xl"><p className="mb-8 text-xs font-bold uppercase tracking-[.25em] text-white/65">Identidad</p><h2 className="display max-w-5xl text-[clamp(2.8rem,6vw,7rem)] font-bold leading-[.9] tracking-[-.08em]">No somos solamente un club. Somos generaciones jugando la misma camiseta.</h2></motion.div></section>

  <section id="basquet" className="px-6 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="El deporte" title="El básquet es Welcome." /><div className="mt-14 grid gap-5 md:grid-cols-3">{basketballGroups.map((group, index) => <motion.a initial="hidden" whileInView="visible" viewport={{ once: true, amount: .2 }} variants={{ hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: .7, ease: "easeOut", delay: index * .1 } } }} key={group.title} href={group.href} className="group relative min-h-[30rem] overflow-hidden bg-[var(--welcome-black)] text-white"><MediaPlaceholder className="absolute inset-0 min-h-0 opacity-55 transition-transform duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black via-black/30 to-transparent" /><div className="relative flex h-full flex-col justify-end p-7"><span className="mb-auto text-xs font-bold text-white/50">0{index + 1}</span><h3 className="display text-4xl font-bold tracking-[-.06em]">{group.title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-white/65">{group.text}</p><span className="mt-6 flex items-center gap-2 text-sm font-bold text-[var(--welcome-red-light)]">Conocé más <ChevronRight size={17} className="transition-transform group-hover:translate-x-1" /></span></div></motion.a>)}</div></div></section>

  <section id="socios" className="bg-[var(--welcome-black)] px-6 py-24 text-white lg:px-10 lg:py-36"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.1fr_1fr] lg:items-end"><div><SectionHeading dark eyebrow="Pertenencia" title="Hacete parte de Welcome." /><p className="mt-8 max-w-md leading-7 text-white/60">La información sobre modalidades, beneficios y contacto se agregará cuando esté confirmada.</p><a href="#contacto" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[var(--welcome-red)] px-6 py-4 text-sm font-bold">Hacete socio <ArrowUpRight size={17} /></a></div><div className="grid gap-7 border-t border-white/15 pt-7">{["Contactanos", "Elegí cómo sumarte", "Viví Welcome"].map((step, index) => <div key={step} className="flex gap-5 border-b border-white/15 pb-7"><span className="text-sm text-[var(--welcome-red-light)]">0{index + 1}</span><div><h3 className="text-xl font-bold">{step}</h3><p className="mt-2 text-sm text-white/45">Detalle pendiente de completar.</p></div></div>)}</div></div></section>

  <section id="historia" className="px-6 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Legado" title={<>Una camiseta.<br /><span className="text-[var(--welcome-red)]">Generaciones de historia.</span></>} /><div className="mt-16 grid gap-0 border-t border-black/15 md:grid-cols-3">{timeline.map((item, index) => <div key={`${item.year}-${item.title}-${index}`} className="border-b border-black/15 py-8 md:border-r md:px-7 md:first:pl-0"><p className="display text-5xl font-bold tracking-[-.08em] text-[var(--welcome-red)]">{item.year}</p><h3 className="mt-5 font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-black/55">{item.text}</p></div>)}</div><Link href="/historia" className="mt-10 inline-flex items-center gap-2 text-sm font-bold underline decoration-[var(--welcome-red)] decoration-2 underline-offset-8">Conocé nuestra historia <ArrowUpRight size={16} /></Link></div></section>

  <section className="grid bg-[var(--welcome-red)] text-white lg:grid-cols-2"><MediaPlaceholder className="min-h-[28rem] opacity-25" /><div className="flex flex-col justify-center px-6 py-20 lg:px-16"><p className="text-xs font-bold uppercase tracking-[.25em] text-white/65">Formativas</p><h2 className="display mt-5 text-5xl font-bold leading-[.9] tracking-[-.08em] lg:text-7xl">Crecer también es jugar.</h2><p className="mt-7 max-w-sm leading-7 text-white/75">Contenido sobre edades, actividades y propuestas pendiente de completar.</p><Link href="/basquet/formativas" className="mt-8 inline-flex items-center gap-2 text-sm font-bold underline underline-offset-8">Conocé las formativas <ArrowUpRight size={16} /></Link></div></section>

  <section id="noticias" className="px-6 py-24 lg:px-10 lg:py-36"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionHeading eyebrow="Actualidad" title="Noticias." /><Link href="/noticias" className="inline-flex items-center gap-2 text-sm font-bold">Ver todas <ArrowUpRight size={16} /></Link></div><div className="mt-14 grid gap-8 md:grid-cols-3">{newsItems.map((item) => <article key={item.title}><MediaPlaceholder className="aspect-[4/3] min-h-0" /><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-[var(--welcome-red)]">{item.category} · {item.date}</p><h3 className="display mt-3 text-2xl font-bold leading-tight tracking-[-.05em]">{item.title}</h3></article>)}</div></div></section>

  <section id="contacto" className="bg-[var(--welcome-red)] px-6 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-white/65">El próximo capítulo</p><h2 className="display mt-6 max-w-4xl text-[clamp(3rem,7vw,8rem)] font-bold leading-[.85] tracking-[-.09em]">Welcome se vive desde adentro.</h2><div className="mt-10 flex flex-wrap gap-3"><a href="#socios" className="rounded-full bg-white px-6 py-4 text-sm font-bold text-black">Hacete socio</a><a href="#contacto" className="rounded-full border border-white/40 px-6 py-4 text-sm font-bold">Contactanos</a></div></div></section>
  </main>; }

function SectionHeading({ eyebrow, title, dark = false }: { eyebrow: string; title: React.ReactNode; dark?: boolean }) { return <div className={dark ? "text-white" : ""}><p className={`text-xs font-bold uppercase tracking-[.25em] ${dark ? "text-[var(--welcome-red-light)]" : "text-[var(--welcome-red)]"}`}>{eyebrow}</p><h2 className="display mt-5 text-[clamp(2.8rem,5vw,6rem)] font-bold leading-[.88] tracking-[-.08em]">{title}</h2></div>; }
